version: "3"
services:
  next:
    container_name: studion_frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - ./:/usr/src/app
    stdin_open: true
