version: "3"
services:
  next:
    container_name: studion_frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "3060:3000"
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - ./:/usr/src/app
    stdin_open: true

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/bin/docker-compose
    ports:
      - "8080:8080"
    privileged: true
    user: root
