import type { NextPage } from 'next'
import Head from 'next/head'
import AppLayout from '../components/common/AppLayout'

import MainSection from '../components/main/MainSection'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>STUDION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        {/* main section */}
        <MainSection/>
      </AppLayout>
    </div>
  )
}

export default Home
